### ISSUE TITLE
Adding ellipse/oval shape in the list of stock-tools annotations

### ISSUE THREAD

**Issue by ivan-stojanov** [highcharts/highcharts#15008]
# Description of the feature
Adding an ellipse/oval annotation as a part of "[stock-tools](https://www.highcharts.com/docs/stock/stock-tools)" annotations. 

From user perspective, at the moment circle annotation is the most similar one, but there is an "issue" with the way it behaves: 
- circle annotation has a single point like that and it is the center of the circle. The radius is constant and not tied to any axis, so when changing the zoom levels of the chart, the circle is keeps it's radius;
- what end user would want is to be able to draw annotations which are tied to the X/Y axis and the annotation to keep points on which was drawn to;
- the above points, would result with having new type of ellipse/oval annotation;

# Library related to the feature
- highstock: https://code.highcharts.com/stock/highstock.js
- annotations: https://code.highcharts.com/modules/annotations.js
- annotations advanced: https://code.highcharts.com/modules/annotations-advanced.js
- stock tools: https://code.highcharts.com/modules/stock-tools.js

# Proof of Concept/Live example for the feature
There are a few ideas of how this can work, but from implementation point of view, I am not sure how much my comments will be relevant to the fact if the source code can support them.
- if somehow the rectangle annotation can be reused, with the ability to round up it's corners (if they are round up enough, this will result with an oval shape). Not sure how much this is relevant, but using the SVG rendered, I was able to draw an oval shape. Here is my implementation for this: https://jsfiddle.net/delux123/qeuk17gj/ where drawing is done with click-and-drag to draw. Since this is an SVG, it's still not the annotation concept that I am suggesting and the object it's still not tied to the X/Y axes;
- if it's not feasible, it doesn't have to be drawn on the same was as circle is. For example, here is an alternative: draw a line between two points (and keep the both points as the left vertex and right vertex of the ellipse). When the second vertex is released, the line between the two vertices will represent "major axis". But drawing does not ends here and the center of the major axis is detected and in this center the two co-vertices are initiated (but not drawn yet). The X values of the co-vertices are defined based on the center of the major axis (in the angle of 90 degrees). As the user moves the mouse, the values from Y axis of the current mouse position are bind to the Y values of the both co-vertices and they are following the user. Once clicked again, the drawing ends and co-vertices are placed. I found something similar [in the following video](https://screencast-o-matic.com/watch/crVuXOR1ka). 

![ellipse example](https://www.mathwarehouse.com/ellipse/images/picture-of-ellipse.gif)

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawelfus** [comment]
# Todo's:
- [ ] - create new annotation type (see [other types](https://github.com/highcharts/highcharts/tree/master/ts/Extensions/Annotations/Types))
- [ ] - add to `annotations-advanced` module
- [ ] - add to [API](https://api.highcharts.com/highstock/annotations)
- [ ] - create a demo (similar to [this one](https://jsfiddle.net/BlackLabel/fxp3L96s/))
- [ ] - add to Stock Tools ([icon](https://github.com/highcharts/highcharts/blob/master/gfx/stock-icons/ellipse.svg))

**Comment by Maquendi** [comment]
Hi, do you guys have a date when new ellipse annotation will become available ?? thanx !!!

**Comment by pawelfus** [comment]
Hi @Maquendi 

We are aiming for the next release, probably within a few weeks :)
