### ISSUE TITLE
Stock Annotations: Fibonacci Timezones

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15825]
# Description of the feature
Add a Fibonacci timezones annotation. Indicates Fibonacci intervals on the timeline.

- Each vertical line should have a label with a value
- Two control points:
  - one to control where the first line is rendered
  - second one to control the distance between the 1st and the 2nd (4th?) vertical line
- API options similar to Fibonacci annotations (probably implementation can be based on that Class too)

# Library related to the feature
Highcharts Stock

# Proof of Concept/Live example for the feature
![Zrzut ekranu 2021-06-1 o 15 34 03](https://user-images.githubusercontent.com/1453926/120332782-5c831980-c2ef-11eb-9bfa-8a1fee1fd9a1.png)

# Todo's:
- [x] - create new annotation type (see [other types](https://github.com/highcharts/highcharts/tree/master/ts/Extensions/Annotations/Types))
- [x] - add to `annotations-advanced` module
- [x] - add to [API](https://api.highcharts.com/highstock/annotations)
- [x] - create a demo (similar to [this one](https://jsfiddle.net/BlackLabel/fxp3L96s/))
- [x] - add to Stock Tools ([icon](https://github.com/highcharts/highcharts/blob/master/gfx/stock-icons/fibonacci-timezone.svg))
----

**You can vote for this feature by adding a thumbs-up reaction to this post.**
