### ISSUE TITLE
Implement styled mode as an option.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#8922]
With this enhancement, we serve only one built file, and styled mode will be toggled with a simple option, `chart.styledMode`.

Implementation is done in the [hc7/styled-mode](https://github.com/highcharts/highcharts/tree/hc7/styled-mode) branch.

#### Implementation plan
 - [x] Remove supercode comments and replace with inline check for `Chart.styledMode` or `Renderer.styledMode`.
 - [x] Identify and implement a structure for dual-mode option defaults, namely `tooltip.pointFormat` and `tooltip.headerFormat`.
 - [x] Set up unit tests for various series types. The tests should check that presentational attributes (`fill`, `stroke`, `style` etc) are not set in the generated SVG. All series types should be tested, and new series types and features should be caught.
 - [x] Update all demos to use the root level `highcharts.js` file, and set the `chart.styledMode` option.
 - [x] Decide how to serve the legacy styled-mode file structure (`code.highcharts.com/js/...`). Decided to not serve new files.
 - [ ] Turn off building of styled mode files in assembler/tools.

**Comment by TorsteinHonsi** [comment]
Decision for serving: Don't build and serve new files. v6 files will be served from code.highcharts.com root level.

**Comment by TorsteinHonsi** [comment]
Not completely finished, see check boxes.
